spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
todos:
  webui:
    placeholder: "Add a TODO item ..."
    username: Test User
management:
  metrics:
    export:
      wavefront:
        uri: https://vmware.wavefront.com
        apiToken: <TOKEN>
        step: PT10S
          #proxy:
          #host: wavefront-proxy.wavefront.svc.cluster.local
          #port: 2878
        #histogram_port: 40000
        #tracing_port:  30000

        reporting:
          #duration=(reporting duration, intervals between spring micrometer reporting)
          traces: true

        application:
          name: Todos Application
          service: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
