apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: todos-demo-store-bellsoft
spec:
  sources:
  # Removed - - image: gcr.io/paketo-buildpacks/adopt-openjdk
  # Add
  - image: gcr.io/paketo-buildpacks/bellsoft-liberica
  - image: gcr.io/paketo-buildpacks/gradle
  - image: gcr.io/paketo-buildpacks/maven
  - image: gcr.io/paketo-buildpacks/executable-jar
  - image: gcr.io/paketo-buildpacks/apache-tomcat
  - image: gcr.io/paketo-buildpacks/spring-boot
  - image: gcr.io/paketo-buildpacks/dist-zip