apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomClusterBuilder
metadata:
  name: todos-demo-cluster-builder
spec:
  tag: triathlonguy/custom-builder
  stack: base-cnb
  store: todos-demo-store
  serviceAccountRef:
    name: ccb-service-account
    namespace: build-service
  order:
  - group:
    - id: paketo-buildpacks/adopt-openjdk
    - id: paketo-buildpacks/gradle
      optional: true
    - id: paketo-buildpacks/maven
      optional: true
    - id: paketo-buildpacks/executable-jar
      optional: true
    - id: paketo-buildpacks/apache-tomcat
      optional: true
    - id: paketo-buildpacks/spring-boot
      optional: true
    - id: paketo-buildpacks/dist-zip
      optional: true