apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bellsoft-liberica
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "gcr.io/paketo-buildpacks/build:base-cnb"
  runImage:
    image: "gcr.io/paketo-buildpacks/run:base-cnb"