apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomClusterBuilder
metadata:
  name: todos-demo-cluster-managed-builder
spec:
  tag: triathlonguy/custom-managed-builder
  stack: managed-stack
  store: todos-demo-store-managed
  serviceAccountRef:
    name: ccb-service-account
    namespace: build-service
  order:  
  - group:
    - id: org.cloudfoundry.openjdk
    - id: org.cloudfoundry.buildsystem
      optional: true
    - id: org.cloudfoundry.jvmapplication
      optional: true
    - id: org.cloudfoundry.tomcat
      optional: true
    - id: org.cloudfoundry.springboot
      optional: true
    - id: org.cloudfoundry.distzip
      optional: true  

  